@extends('layouts.admin')
@section('title','Marketing') @section('heading','Marketing')
@section('actions')<a class="button small" href="{{ route('admin.index') }}">Admin dashboard</a>@endsection
@section('content')
<div class="metrics"><article><span>Contacts</span><strong>{{ number_format($contactStats['total']) }}</strong><small>All time</small></article><article><span>Consented</span><strong>{{ number_format($contactStats['consented']) }}</strong><small>Eligible to receive campaigns</small></article><article><span>Opted out</span><strong>{{ number_format($contactStats['opted_out']) }}</strong><small>Suppressed permanently</small></article></div>
<div class="dashboard-grid">
<section class="panel"><div class="panel-head"><div><span>Audience</span><h2>Add a contact</h2></div></div><form method="POST" action="{{ route('portal.contacts.store',$organization) }}" class="stack-form compact">@csrf<label>Phone (E.164)<input name="phone" value="{{ old('phone') }}" placeholder="+237670000000" required></label><label>Name (optional)<input name="name" value="{{ old('name') }}" placeholder="Ada Lovelace"></label><label>Consent<select name="consent_status"><option value="consented" @selected(old('consent_status','consented')==='consented')>Consented</option><option value="unknown" @selected(old('consent_status')==='unknown')>Unknown</option><option value="opted_out" @selected(old('consent_status')==='opted_out')>Opted out</option></select></label><label>Consent source<input name="consent_source" value="{{ old('consent_source') }}" placeholder="Web signup form"><small>Required when consent is “Consented”. Keep evidence of how consent was collected.</small></label><button class="button">Save contact</button></form></section>
<section class="panel span-2"><div class="panel-head"><div><span>Recipients</span><h2>Contacts</h2></div><small>{{ $contacts->total() }} total</small></div><div class="table-wrap"><table><thead><tr><th>Phone</th><th>Name</th><th>Consent</th><th>Added</th></tr></thead><tbody>@forelse($contacts as $contact)<tr><td class="mono">{{ $contact->phone }}</td><td>{{ $contact->name ?? '—' }}</td><td><span class="status {{ $contact->consent_status->value === 'consented' ? 'delivered' : ($contact->consent_status->value === 'opted_out' ? 'failed' : 'queued') }}">{{ str_replace('_',' ',$contact->consent_status->value) }}</span></td><td>{{ $contact->created_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="4" class="empty">No contacts yet. Add consented recipients to run campaigns.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $contacts->links() }}</div></section>
</div>
<div class="dashboard-grid">
<section class="panel"><div class="panel-head"><div><span>Outreach</span><h2>New campaign</h2></div></div>@if($consentedContacts->isEmpty())<div class="empty">Add at least one consented contact before launching a campaign.</div>@else<form method="POST" action="{{ route('portal.campaigns.store',$organization) }}" class="stack-form compact">@csrf<label>Campaign name<input name="name" value="{{ old('name') }}" placeholder="July promotion" required></label><label>Message<textarea name="content" rows="3" maxlength="1600" placeholder="Hi {name}, …" required>{{ old('content') }}</textarea><small>Only consented, non-suppressed contacts are queued. Opt-outs (STOP/ARRET) are honored automatically.</small></label><label>Schedule (optional)<input type="datetime-local" name="send_at" value="{{ old('send_at') }}"></label><fieldset class="scroll-list"><legend>Recipients ({{ $consentedContacts->count() }} consented)</legend>@foreach($consentedContacts as $contact)<label class="check-row"><input type="checkbox" name="contact_ids[]" value="{{ $contact->id }}"> {{ $contact->name ? $contact->name.' · ' : '' }}{{ $contact->phone }}</label>@endforeach</fieldset><button class="button">Launch campaign</button></form>@endif</section>
<section class="panel span-2"><div class="panel-head"><div><span>History</span><h2>Campaigns</h2></div></div><div class="key-list">@forelse($campaigns as $campaign)<article><div><strong>{{ $campaign->name }}</strong><small>{{ $campaign->recipient_count }} queued · {{ $campaign->suppressed_count }} suppressed · {{ $campaign->launched_at?->diffForHumans() }}</small></div><span class="status {{ $campaign->status->value === 'failed' ? 'failed' : 'delivered' }}">{{ $campaign->status->value }}</span></article>@empty<div class="empty">No campaigns yet.</div>@endforelse</div></section>
</div>
@endsection
