expose_php=Off
display_errors=Off
log_errors=On
memory_limit=256M
post_max_size=12M
upload_max_filesize=10M
max_execution_time=60
opcache.enable=1
opcache.validate_timestamps=0
opcache.memory_consumption=192
session.cookie_httponly=1
session.cookie_secure=1
session.cookie_samesite=Lax
