<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="HTSMS turns your Android phone and SIM into a secure programmable SMS gateway.">
    <title>HTSMS — Your SIM. Your gateway.</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="marketing">
<header class="site-header wrap"><a class="brand" href="{{ route('home') }}"><span>HT</span>SMS</a><nav><a href="#how">How it works</a><a href="#features">Features</a><a href="{{ asset('downloads/htsms-gateway-v0.2.0-beta.apk') }}" download>Android app</a><a href="{{ route('login') }}">Sign in</a><a class="button small" href="{{ route('register') }}">Start building</a></nav></header>
<main>
    <section class="hero wrap"><div class="hero-copy"><div class="eyebrow">Built for businesses in Cameroon and beyond</div><h1>Your Android phone is now an <em>SMS API.</em></h1><p>Connect your own phone and SIM, send transactional messages from a clean API, and monitor every delivery from one secure workspace.</p><div class="hero-actions"><a class="button" href="{{ route('register') }}">Create your workspace</a><a class="text-link" href="#how">See how it works →</a></div><div class="trust-row"><span>Proprietary platform</span><span>Dual-SIM ready</span><span>Revocable credentials</span></div></div><div class="phone-stage"><div class="signal-card"><span class="signal-dot"></span><div><strong>Office Gateway</strong><small>Online · Orange CM</small></div><b>84%</b></div><div class="phone"><div class="phone-top"></div><div class="phone-screen"><div class="mini-brand">HTSMS Gateway</div><div class="gateway-ring"><span>Connected</span><strong>128</strong><small>sent today</small></div><div class="sim-row"><div><small>SIM 1</small><b>Orange CM</b></div><div><small>Queue</small><b>3 messages</b></div></div></div></div><div class="delivery-card"><div class="check">✓</div><div><strong>Message delivered</strong><small>+237 6•• ••• 418 · 2s ago</small></div></div></div></section>
    <section id="how" class="section wrap"><div class="section-heading"><span>Simple by design</span><h2>From phone to production in minutes</h2></div><div class="steps"><article><b>01</b><h3>Create a workspace</h3><p>Register your business and create a secure, tenant-isolated workspace.</p></article><article><b>02</b><h3>Install and scan</h3><p><a class="inline-download" href="{{ asset('downloads/htsms-gateway-v0.2.0-beta.apk') }}" download>Download the HTSMS Gateway beta</a>, install it, then scan the secure QR from your Devices page.</p></article><article><b>03</b><h3>Send through the API</h3><p>Create a scoped API key and start sending with delivery status tracking.</p></article></div></section>
    <section id="features" class="feature-band"><div class="wrap feature-grid"><div><span class="eyebrow">Control stays with you</span><h2>Infrastructure you can hold in your hand.</h2><p>Your business supplies the phone and mobile plan. HTSMS supplies secure orchestration, developer tooling, audit trails, and operational visibility.</p></div><div class="feature-list"><div><b>Transactional API</b><span>Idempotent requests and predictable message states.</span></div><div><b>Device security</b><span>One-time pairing and instantly revocable credentials.</span></div><div><b>Live operations</b><span>Battery, connectivity, SIM, queue, and delivery health.</span></div><div><b>Built for teams</b><span>Organization roles and scoped developer keys.</span></div></div></div></section>
</main>
<footer class="wrap"><a class="brand" href="/"><span>HT</span>SMS</a><a class="support-link" href="mailto:{{ config('app.support_email') }}">Customer support: {{ config('app.support_email') }}</a><p>© {{ date('Y') }} CM-EA. Proprietary software.</p></footer>
</body></html>
