@extends('layouts.portal')
@section('title','Developer') @section('heading','Developer settings')
@section('content')
@if(session('plain_text_key'))<section class="secret-reveal"><div><span>Your new API key</span><strong id="api-secret">{{ session('plain_text_key') }}</strong><small>Copy this now. HTSMS stores only its hash and cannot show it again.</small></div><button type="button" data-copy="#api-secret">Copy key</button></section>@endif
<div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><span>Credentials</span><h2>Create an API key</h2></div></div><form method="POST" action="{{ route('portal.api-keys.store',$organization) }}" class="stack-form compact">@csrf<label>Key name<input name="name" placeholder="Production backend" required></label><fieldset><legend>Permissions</legend><label class="check-row"><input type="checkbox" name="abilities[]" value="messages:read" checked> Read messages</label><label class="check-row"><input type="checkbox" name="abilities[]" value="messages:write" checked> Send messages</label></fieldset><label>Expiry (optional)<input type="date" name="expires_at"></label><button class="button">Create secret key</button></form></section><section class="panel span-2"><div class="panel-head"><div><span>Active credentials</span><h2>API keys</h2></div><a href="/docs">API documentation →</a></div><div class="key-list">@forelse($apiKeys as $key)<article><div><strong>{{ $key->name }}</strong><code>htsms_live_{{ $key->prefix }}••••••</code><small>{{ implode(' · ',$key->abilities) }} · {{ $key->last_used_at ? 'Used '.$key->last_used_at->diffForHumans() : 'Never used' }}</small></div><span class="status {{ $key->revoked_at ? 'failed' : 'delivered' }}">{{ $key->revoked_at ? 'revoked' : 'active' }}</span>@if(!$key->revoked_at)<form method="POST" action="{{ route('portal.api-keys.revoke',[$organization,$key]) }}">@csrf @method('DELETE')<button class="danger-link">Revoke</button></form>@endif</article>@empty<div class="empty">No API keys yet.</div>@endforelse</div></section></div>
<section class="panel code-panel"><div class="panel-head"><div><span>Quick start</span><h2>Send your first message</h2></div></div><pre><code>curl -X POST {{ url('/api/v1/messages') }} \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Idempotency-Key: order-1001" \
  -H "Content-Type: application/json" \
  -d '{"to":"+237670000000","content":"Your order is ready."}'</code></pre></section>
@endsection
