@extends('layouts.portal')
@section('title','Developer') @section('heading','Developer settings')
@section('content')
@if(session('plain_text_key'))<section class="secret-reveal"><div><span>Your new API key</span><strong id="api-secret">{{ session('plain_text_key') }}</strong><small>Copy this now. HTSMS stores only its hash and cannot show it again.</small></div><button type="button" data-copy="#api-secret">Copy key</button></section>@endif
<div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><span>Credentials</span><h2>Create an API key</h2></div></div><form method="POST" action="{{ route('portal.api-keys.store',$organization) }}" class="stack-form compact">@csrf<label>Key name<input name="name" placeholder="Production backend" required></label><fieldset><legend>Permissions</legend><label class="check-row"><input type="checkbox" name="abilities[]" value="messages:read" checked> Read messages</label><label class="check-row"><input type="checkbox" name="abilities[]" value="messages:write" checked> Send messages</label></fieldset><label>Expiry (optional)<input type="date" name="expires_at"></label><button class="button">Create secret key</button></form></section><section class="panel span-2"><div class="panel-head"><div><span>Active credentials</span><h2>API keys</h2></div><a href="https://github.com/Nekoutb/htsms/blob/main/docs/API.md" target="_blank" rel="noopener">API documentation →</a></div><div class="key-list">@forelse($apiKeys as $key)<article><div><strong>{{ $key->name }}</strong><code>htsms_live_{{ $key->prefix }}••••••</code><small>{{ implode(' · ',$key->abilities) }} · {{ $key->last_used_at ? 'Used '.$key->last_used_at->diffForHumans() : 'Never used' }}</small></div><span class="status {{ $key->revoked_at ? 'failed' : 'delivered' }}">{{ $key->revoked_at ? 'revoked' : 'active' }}</span>@if(!$key->revoked_at)<form method="POST" action="{{ route('portal.api-keys.revoke',[$organization,$key]) }}">@csrf @method('DELETE')<button class="danger-link">Revoke</button></form>@endif</article>@empty<div class="empty">No API keys yet.</div>@endforelse</div></section></div>
<section class="panel code-panel"><div class="panel-head"><div><span>External API</span><h2>Send and read messages</h2></div><small>Use a key with messages:read and/or messages:write.</small></div><pre><code># Send an outbound message
curl -X POST {{ url('/api/v1/messages') }} \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -H "Idempotency-Key: order-1001" \
  -H "Content-Type: application/json" \
  -d '{"to":"+237670000000","content":"Your order is ready."}'

# Read outbound messages
curl {{ url('/api/v1/messages') }} \
  -H "Authorization: Bearer YOUR_API_KEY"

# Read inbound messages
curl {{ url('/api/v1/inbound-messages') }} \
  -H "Authorization: Bearer YOUR_API_KEY"</code></pre></section>
@if(session('plain_text_webhook_secret'))<section class="secret-reveal"><div><span>Your new webhook signing secret</span><strong id="webhook-secret">{{ session('plain_text_webhook_secret') }}</strong><small>Copy this now. HTSMS stores only its hash and cannot show it again. Verify each delivery with HMAC-SHA256.</small></div><button type="button" data-copy="#webhook-secret">Copy secret</button></section>@endif
<div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><span>Event delivery</span><h2>Add a webhook</h2></div></div><form method="POST" action="{{ route('portal.webhooks.store',$organization) }}" class="stack-form compact">@csrf<label>Name<input name="name" placeholder="Order service" required></label><label>HTTPS endpoint<input name="url" type="url" placeholder="https://api.example.com/htsms" required><small>Must be public HTTPS. Private and reserved addresses are rejected.</small></label><fieldset><legend>Events</legend>@foreach($webhookEvents as $event)<label class="check-row"><input type="checkbox" name="events[]" value="{{ $event->value }}" @checked(in_array($event->value,['message.delivered','message.failed'],true))> {{ $event->value }}</label>@endforeach</fieldset><button class="button">Create webhook</button></form></section><section class="panel span-2"><div class="panel-head"><div><span>Active endpoints</span><h2>Webhooks</h2></div></div><div class="key-list">@forelse($webhooks as $endpoint)<article><div><strong>{{ $endpoint->name }}</strong><code class="mono">{{ $endpoint->url }}</code><small>{{ implode(' · ',$endpoint->events) }}@if($endpoint->consecutive_failures) · {{ $endpoint->consecutive_failures }} recent failures @endif</small></div><span class="status {{ $endpoint->is_active ? 'delivered' : 'failed' }}">{{ $endpoint->is_active ? 'active' : 'disabled' }}</span>@if($endpoint->is_active)<form method="POST" action="{{ route('portal.webhooks.revoke',[$organization,$endpoint]) }}" data-confirm="Disable this webhook endpoint?">@csrf @method('DELETE')<button class="danger-link">Disable</button></form>@endif</article>@empty<div class="empty">No webhooks yet. Add one to receive delivery and inbound events.</div>@endforelse</div></section></div>
@endsection
